#!/bin/bash
# vim: set ft=bash

PROGRAM_NAME=cgrep
GREP=grep
GREPFLAGS="--perl-regexp --dereference-recursive --line-number --max-count=1 --color=always"
INCLUDES=/usr/include

show_usage () {
    echo "Usage: $PROGRAM_NAME [COMMAND] [TERM]"
    echo ""
    echo "Commands:"
    echo "      c           search for constant"
    echo "      f           search for function"
    echo "      s           search for struct"
    echo ""
    echo "Examples:"
    echo ""
    echo "      # Search for defined constant AF_INET"
    echo "      $ cgrep c AF_INET"
    echo ""
    echo "      # Search for function inet_pton"
    echo "      $ cgrep f inet_pton"
    echo ""
    echo "      # Search for struct sockaddr_in"
    echo "      $ cgrep s sockaddr_in"
}

print_results () {
    echo $1
}
    
if [ "$#" -lt 2 ]; then
    show_usage
    exit 1
fi

case $1 in
    c) 
        $GREP $GREPFLAGS "^#define[ \t]*$2[ \t]" $INCLUDES 2>/dev/null
        exit 0
        ;;
    f)
        $GREP $GREPFLAGS "[ \t]$2[ \t\n]\(" $INCLUDES 2>/dev/null
        exit 0
        ;;
    s)
        $GREP $GREPFLAGS "struct $2 \{" $INCLUDES 2>/dev/null
        exit 0
        ;;
    *)
        show_usage
        exit 1
        ;;
esac
