#!/usr/bin/env python2
# vim: set ft=python
import math
import pefile
import sys
from tabulate import tabulate

def byte_count(data):
    count = [0] * 256
    for b in data:
        count[b] += 1
    return count

def entropy(data):
    data = map(ord, data)
    data_len = len(data)

    counts = [0]*256
    for b in data:
        counts[b] += 1

    ent = 0
    for count in counts:
        if count != 0:
            p = 1.0 * count / data_len
            ent -= p * math.log(p, 256)
    return ent

def print_sections(pe):
    sections = [(s.Name.rstrip("\x00"), hex(s.VirtualAddress), hex(s.Misc_VirtualSize), hex(s.SizeOfRawData), entropy(s.get_data())) for s in pe.sections]
    headers = ("NAME", "VIRTUAL ADDRESS", "VIRTUAL SIZE", "SIZE OF RAW DATA", "ENTROPY")
    print(tabulate(sections, headers=headers, tablefmt="fancy_grid"))

def print_resources(pe):
    for rsrc in pe.DIRECTORY_ENTRY_RESOURCE.entries:
        for entry in rsrc.directory.entries:
            print(entry.name)

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: peinfo <filename>")
        exit(1)

    pe = pefile.PE(sys.argv[1])

    print_sections(pe)
    print_resources(pe)
