#!/usr/bin/env python3
import string
import sys

def rotn(data, n):
    data = data.encode("utf-8")
    l = string.ascii_lowercase.encode("utf-8")
    u = string.ascii_uppercase.encode("utf-8")
    t = bytes.maketrans(l + u, l[n:] + l[:n] + u[n:] + u[:n]) 
    return bytes.translate(data, t).decode("utf-8")

if __name__ == "__main__":
    
    if len(sys.argv) < 2:
        print("Usage: rotn STRING")
        exit(1)

    data = sys.argv[1]
    for i in range(26):
        print("rot-{}:\t{}".format(i, rotn(data, i)))

