#!/bin/bash
# vim: set ft=bash

if [ "$#" -lt 1 ]; then
    echo "Usage: xrandr-single OUTPUT-NAME"
    exit 1
fi

output=$1

if ! xrandr -q | grep "$output connected" 1>/dev/null; then
    echo "Output not found (or not connected): $output"
    exit 1
fi

for other in $(xrandr -q | grep " connected" | grep -v $1 | cut -d" " -f1); do
    xrandr --output $other --off
done

xrandr --output $output --auto --primary
